pub mod wasm_exports;
mod wasm_error;
mod boolean_button;
mod simulation_program;
mod camera;
mod dispatch_event;
mod web_utils;
mod shaders;
mod pixels_render;
mod blur_render;
mod internal_resolution_render;
mod rgb_render;
mod event_listeners;
mod simulation_state;
mod action_bindings;
mod console;
mod render_types;